#Plan to be refined considering possible obstacles along the path
nav_msgs/Path plan

# If the goal is obstructed, how many meters the planner can
# relax the constraint in x and y before failing.
float32 tolerance
---
#Refined plan
nav_msgs/Path refined_plan

# Every two consecutive poses are referring to the 
# last free pose before an obstacle and the first free pose after it,
# For example if there were 3 obstacles along the original plan,
# this array will contain 6 poses
geometry_msgs/PoseArray obstacles_boundary

#True if refining the given plan was possible, otherwise False
bool success
